pretrained_model_path: "./stable-diffusion-v1-5"
pretrained_vae_path: "./sd-vae-ft-mse"
pretrained_controlnet_path: "./MagicAnimate/densepose_controlnet"
pretrained_appearance_encoder_path: "./MagicAnimate/appearance_encoder"
pretrained_unet_path: ""

motion_module: "./MagicAnimate/temporal_attention/temporal_attention.ckpt"

savename: null

fusion_blocks: "midup"

seed:           [1]
steps:          25
guidance_scale: 7.5

source_image:
  - "inputs/applications/source_image/monalisa.png"
  - "inputs/applications/source_image/0002.png"
  - "inputs/applications/source_image/demo4.png"
  - "inputs/applications/source_image/dalle2.jpeg"
  - "inputs/applications/source_image/dalle8.jpeg"
  - "inputs/applications/source_image/multi1_source.png"
video_path:
  - "inputs/applications/driving/densepose/running.mp4"
  - "inputs/applications/driving/densepose/demo4.mp4"
  - "inputs/applications/driving/densepose/demo4.mp4"
  - "inputs/applications/driving/densepose/running2.mp4"
  - "inputs/applications/driving/densepose/dancing2.mp4"
  - "inputs/applications/driving/densepose/multi_dancing.mp4"

inference_config: "configs/inference/magic_inference.yaml"
size: [768, 512]
L:    8
S:    1
I:    0
clip: 0
offset: 0
max_length: null
video_type: "condition"
invert_video: false
save_individual_videos: false
